/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_appkey_AppKey */

#ifndef _Included_com_example_appkey_AppKey
#define _Included_com_example_appkey_AppKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_appkey_AppKey
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_appkey_AppKey_getKey
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
